### ISSUE TITLE
Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.EnvVarFluent$ValueFromNested

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-argocd#108]
## Issue

This project is getting the following error when the module `cli` tries to generate the k8s resources.
That error arrives since I bumped the version of Quarkus from 3.15 to 3.27 and is related to the fact that dekorate is still designed around an old version of the f8 kubernetes client: 6.13 which is now 2 years old and has been replaced in quarkus with a more recent version: 7.3.1

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.27.1:build (default) on project quarkus-argocd-cli: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.EnvVarFluent$ValueFromNested io.fabric8.kubernetes.api.model.ContainerFluent$EnvNested.withNewValueFrom()'
[ERROR]         at io.dekorate.kubernetes.decorator.DeploymentResourceFactory.createPodSpec(DeploymentResourceFactory.java:77)
[ERROR]         at io.dekorate.kubernetes.decorator.DeploymentResourceFactory.createPodTemplateSpec(DeploymentResourceFactory.java:58)
[ERROR]         at io.dekorate.kubernetes.decorator.DeploymentResourceFactory.create(DeploymentResourceFactory.java:52)
[ERROR]         at io.dekorate.AbstractKubernetesManifestGenerator.initializeRegistry(AbstractKubernetesManifestGenerator.java:345)
[ERROR]         at io.dekorate.kubernetes.manifest.KubernetesManifestGenerator.generate(KubernetesManifestGenerator.java:89)
[ERROR]         at io.dekorate.kubernetes.manifest.KubernetesManifestGenerator.generate(KubernetesManifestGenerator.java:62)
[ERROR]         at io.dekorate.Session.lambda$generate$16(Session.java:369)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:186)
[ERROR]         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:803)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:293)
[ERROR]         at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3628)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
[ERROR]         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:632)
[ERROR]         at io.dekorate.Session.generate(Session.java:363)
[ERROR]         at io.dekorate.Session.lambda$generate$5(Session.java:292)
[ERROR]         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[ERROR]         at io.dekorate.Session.generate(Session.java:292)
[ERROR]         at io.dekorate.Session.close(Session.java:256)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$5(KubernetesProcessor.java:197)
[ERROR]         at java.base/java.util.Optional.ifPresent(Optional.java:178)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:140)
```
